# Generated by Django 5.1.1 on 2024-09-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
