# Generated by Django 5.1.1 on 2024-10-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
