# Generated by Django 5.1.1 on 2024-10-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_qtd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='preco_promocional',
            field=models.FloatField(default=0),
        ),
    ]
